### PR TITLE
Integrate local leaderboard/high scores with online (Google Play)

### PR DESCRIPTION
**Pull request by adamajammary**
**Instructions**
1. Sign In
2. Play a level
3. Go back to startup menu
4. Click Online Leaderboard
5. Select Level
6. Your best time for this level is displayed

**Notes**
* You may need to change the settings of your profile to make it public

**Screenshots**

screenshot_20180427-115323 1

screenshot_20180427-121132 1

screenshot_20180427-122449 1

### CODE REVIEW

**Comment by adamajammary** [comment]
Made some changes:
- Closed the dialog before changing the activity (looked like the activity was cancelled mid-way when testing with the second account)
- Reset the online leaderboards (after resetting, it worked for both accounts)

Tested with two different accounts on my mobile to make sure it worked, also tested on another PC.

**Comment by Hifoz** [comment]
Going to test out in emulators to see if it is version specific.

**Comment by Hifoz** [comment]
After testing in an emulator I have the same problem there. My phone runs Android 6.0 while the emulator runs 7.1.1, so it is not version specific. The error message I added in a previous comment does not appear in the emulator, so it is not related to the leaderboard not showing.

**Comment by adamajammary** [comment]
Added some console logs with error priority (so they are easier to filter in the log)

After playing the level and reaching the goal, you should get one of the following logs:

If sign in failed:

	Log.e("MainActivity", "saveTimeToGooglePlay: USER IS NOT SIGNED IN");

If you are successfully signed in:

	1. Log.e("MainActivity", "saveTimeToGooglePlay: USER IS SIGNED IN");
	2. Log.e("GooglePlayService", "updateLeaderboard: UPLOADING SCORE TO GOOGLE PLAY");
	3. Log.e("GooglePlayService", "updateLeaderboard: level=" + level);
	4. Log.e("GooglePlayService", "updateLeaderboard: time=" + time);

After selecting a level, you should get:

	1. Log.e("GooglePlayService", "showLeaderboard: STARTING LEADERBOARD ACTIVITY");
	2. Log.e("GooglePlayService", "showLeaderboard: level_name=" + level);
	3. Log.e("GooglePlayService", "showLeaderboard: level_id=" + level_id);

**Comment by Hifoz** [comment]
The logs show that I was logged in successfully and score was uploaded .When selecting a score, the Log for stating leaderboard activity appears like they should

**Comment by adamajammary** [comment]
Should work now, tested building the app on two PCs, and both could now submit a score and show the leaderboards.

**Note**

I updated the Google Play Services and some other dependencies after the latest Android Studio update.
The project should automatically re-sync everything, but if you get strange red linter errors everywhere,
but building and running the app works fine, it means Android Studio has not updated its caches properly.

You can try one, more or all of the following:
	
1. Close Android Studio
2. Delete the ".idea" and ".gradle" folders in the project folder
3. Start Android Studio
4. File -> Invalidate Caches / Restart
5. File -> Sync Project with Gradle Files
6. Build -> Clean Project

**Comment by Hifoz** [comment]
Looks good now, can view the leaderboard.

**Pull request merged**
